module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "light-gray": "var(--light-gray)",
        onyx: "var(--onyx)",
        "medium-gray": "var(--medium-gray)",
        "light-blue": "var(--light-blue)",
        "dark-grey": "var(--dark-grey)",
        "tg-blue": "var(--tg-blue)",
        charcoal: "var(--charcoal)",
        transparent: "var(--transparent)",
        white: "var(--white)",
        "light-blue-2": "var(--light-blue-2)",
        "moon-light": "var(--moon-light)",
        "gray-60": "var(--gray-60)",
        gray30: "var(--gray30)",
        "border-color-active": "var(--border-color-active)",
        "border-color-hover": "var(--border-color-hover)",
        "list-bg-color": "var(--list-bg-color)",
        "list-text-color": "var(--list-text-color)",
        "list-text-color-hover": "var(--list-text-color-hover)",
        "current-field-text-color": "var(--current-field-text-color)",
        "select-field-arrow-color": "var(--select-field-arrow-color)",
        "list-item-bg-color": "var(--list-item-bg-color)",
        "select-field-padding-left": "var(--select-field-padding-left)",
        "select-field-padding-right": "var(--select-field-padding-right)",
        "list-padding-top-bottom": "var(--list-padding-top-bottom)",
        "list-max-height": "var(--list-max-height)",
        "list-item-padding-left": "var(--list-item-padding-left)",
        "list-item-padding-right": "var(--list-item-padding-right)",
        "list-item-min-height": "var(--list-item-min-height)",
        "list-item-line-height": "var(--list-item-line-height)",
        swiper: {
          "theme-color": "var(--swiper-theme-color)",
          "navigation-size": "var(--swiper-navigation-size)",
        },
        pillRadius: "var(--pill-radius)",
        navPadding: "var(--nav-padding)",
        size: "var(--size)",
        "product-heading-1": "var(--product-heading-1)",
        "product-heading-2": "var(--product-heading-2)",
      },
      fontFamily: {
        sans: ["Arial", "Helvetica", "sans-serif"],
        mono: ["monospace"],
      },
    },
  },
  plugins: [],
};
